name = "aoc"
description = "Advent of Code 2025"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"
website = ""
tags = []

project-files = ["gnat/aoc.gpr"]

[build-switches]
development.optimization = ["-O0"]
development.contracts = "Yes"
development.style_checks = ["-gnaty", "-gnaty-B"]
"*".debug_info = "Yes"
